name: PayTaxPlugin
main: io.github.kuohsuanlo.paytax.PayTaxPlugin
version: ${version}
loadbefore: [essentials]
commands:
  paytax:
    description: .
    aliases: pay
    usage:
  payon:
    description: .
    aliases: pay
    usage: 
  payoff:
    description: .
    usage: